### ISSUE TITLE
Aruba Reporting is not compatible with cucumber 2

### ISSUE THREAD

**Issue by ghost** [cucumber/aruba#256]
@mattwynne @jarl-dk 

I took a look at `aruba/reporting.rb` because of #161. After I upgraded to cucumber 2.0.0, reporting does not work anymore. There seems to be some progress on changing the Formatter API of cucumber.

Does it make sense to refactor the Reporting Module of aruba into a proper cucumber formatter? Seems to be doable and reasonable. What do you think?

References: cucumber/cucumber#839, cucumber/cucumber#851

**Comment by jbpros** [comment]
We're using Aruba's reporting in Cucumber.js's suite. It's broken since we upgraded to Cucumber 2.0.0:

```
      undefined method `line' for #<Cucumber::RunningTestCase::Scenario:0x007fcd0bbabb68> (NoMethodError)
      /Users/jbpros/.gem/ruby/2.1.5/gems/aruba-0.6.2/lib/aruba/reporting.rb:101:in `block in <top (required)>'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/core_ext/instance_exec.rb:25:in `instance_exec'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/core_ext/instance_exec.rb:25:in `block in cucumber_instance_exec'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/core_ext/instance_exec.rb:42:in `cucumber_run_with_backtrace_filtering'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/core_ext/instance_exec.rb:13:in `cucumber_instance_exec'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/rb_support/rb_hook.rb:14:in `invoke'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/runtime/support_code.rb:173:in `block (2 levels) in apply_after_hooks'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/action.rb:22:in `call'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/action.rb:22:in `execute'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/step.rb:31:in `execute'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:99:in `execute'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:46:in `execute'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:24:in `test_step'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/step.rb:16:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:24:in `block (3 levels) in describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:23:in `each'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:23:in `block (2 levels) in describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/filters/prepare_world.rb:22:in `call'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/filters/prepare_world.rb:22:in `block in test_case'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/around_hook.rb:16:in `call'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/around_hook.rb:16:in `execute'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:99:in `execute'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:46:in `execute'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:30:in `around_hook'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/around_hook.rb:11:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:92:in `block (2 levels) in compose_around_hooks'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:93:in `call'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:93:in `compose_around_hooks'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:22:in `block in describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:17:in `call'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/runner.rb:17:in `test_case'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/filters/activate_steps.rb:8:in `test_case'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/filters/quit.rb:11:in `test_case'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/case.rb:21:in `describe_to'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/filter.rb:61:in `done'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/compiler.rb:23:in `done'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core/gherkin/parser.rb:31:in `done'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core.rb:29:in `parse'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-core-1.1.3/lib/cucumber/core.rb:18:in `compile'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/runtime.rb:70:in `run!'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/lib/cucumber/cli/main.rb:38:in `execute!'
      /Users/jbpros/.gem/ruby/2.1.5/gems/cucumber-2.0.0/bin/cucumber:9:in `<top (required)>'
      /Users/jbpros/.gem/ruby/2.1.5/bin/cucumber:23:in `load'
      /Users/jbpros/.gem/ruby/2.1.5/bin/cucumber:23:in `<main>'
```

**Comment by mattwynne** [comment]
I would like to remove Aruba Reporting and stop supporting it. I think it's an old idea. What are you using it for @jbpros?

**Comment by mattwynne** [comment]
Are there any tests that describe how Reporting is supposed to behave?

**Comment by maxmeyer** [comment]
Not really. We can move it to a separate gem to implement a cucumber-formatter?

**Comment by dg-ratiodata** [comment]
@jbpros What are you are using aruba/reporting for? Would that be helpful for you instead? https://github.com/cucumber/aruba/blob/master/features/commands/debug_command.feature

Aruba/Reporting is deprecated and will be removed. So I'm going to close this for now.

**Comment by jbpros** [comment]
We were using it in cucumber.js's own feature suite. But we're actually fine without it.

**Comment by maxmeyer** [comment]
@jbpros But why? What's reason behind this? What are you using it for? Troubleshooting? Generating some kind of documentation?
