### ISSUE TITLE
Remove deprecated methods

### ISSUE THREAD

**Issue by maxmeyer** [cucumber/aruba#265]

**Comment by jasnow** [comment]
Examples I found on 12/6/2015:
```
     -- "The use of "#all_output" is deprecated. Use
        `all_commands.map { |c| c.output }.join("\n") instead. If you
        need to check for some output use "expect(all_commands).to
        have_output /output/" instead. Called by /home/travis/build/
        .../aruba/spec/aruba/api_spec.rb:1112:in `(root)'
     -- The use of "#process_monitor" is deprecated.. Called by 
        /home/travis/build/.../aruba/lib/aruba/api/deprecated.rb:812:in `all_output'
     -- The use of "#assert_not_matching_output" is deprecated. Use
        "expect(command).not_to have_output /partial/" instead. There are
        also special matchers for "stdout" and "stderr". Called by
        /home/travis/build/.../aruba/spec/aruba/api_spec.rb:1116:in `(root)'
     -- The use of "Aruba.platform.unescape" is deprecated. Please use
        "#unescape_text" and "#sanitize_text" instead. But be aware it
        uses a different implementation. Called by /home/travis/build/
        .../aruba/lib/aruba/api/deprecated.rb:618:in `assert_not_matching_output'
```

**Comment by maxmeyer** [comment]
Thanks.

**Comment by mvz** [comment]
Seems to be a duplicate of #396.

**Comment by mvz** [comment]
Duplicate of #396.
