### ISSUE TITLE
`write_file` can get `Errno::ENOENT` on 0.8

### ISSUE THREAD

**Issue by myronmarston** [cucumber/aruba#281]
I tried to [upgrade rspec-core to 0.8](rspec/rspec-core#2028) and I'm getting this new error.  It only appears to happen when the `tmp/aruba` directory does not exist.  If it existed from a prior run things pass OK.  On travis the directory does not exist so [it failed](https://travis-ci.org/rspec/rspec-core/builds/70940563).

Locally I can repro with:

```
➜  rspec-core git:(update-aruba) rm -rf tmp/aruba && bin/rspec spec/integration/order_spec.rb --backtrace
Run options:
  include {:focus=>true}
  exclude {:ruby=>#<Proc:./spec/spec_helper.rb:102>}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 21512

command line
  --order rand
    runs the examples and groups in a different order each time (FAILED - 1)
  --order rand:SEED
    runs the examples and groups in the same order each time (FAILED - 2)
  --seed SEED
    forces '--order rand' and runs the examples and groups in the same order each time (FAILED - 3)
    runs examples in the same order, regardless of the order in which files are given (FAILED - 4)
  --order defined on CLI with --order rand in .rspec
    overrides --order rand with --order defined (FAILED - 5)
  when a custom order is configured
    orders the groups and examples by the provided strategy (FAILED - 6)

Failures:

  1) command line --order rand runs the examples and groups in a different order each time
     Failure/Error: write_file 'spec/simple_spec.rb', "
     Errno::ENOENT:
       No such file or directory @ dir_chdir - /Users/myron/code/rspec-dev/repos/rspec-core/tmp/aruba
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/core.rb:143:in `expand_path'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/filesystem.rb:123:in `write_file'
     # ./spec/integration/order_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./lib/rspec/core/hooks.rb:357:in `instance_exec'
     # ./lib/rspec/core/hooks.rb:357:in `run'
     # ./lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:520:in `each'
     # ./lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:473:in `run'
     # ./lib/rspec/core/example_group.rb:472:in `block in run_before_context_hooks'
     # ./lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
     # ./lib/rspec/core/example_group.rb:471:in `run_before_context_hooks'
     # ./lib/rspec/core/example_group.rb:520:in `run'
     # ./lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./lib/rspec/core/runner.rb:115:in `map'
     # ./lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./lib/rspec/core/configuration.rb:1632:in `with_suite_hooks'
     # ./lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./lib/rspec/core/reporter.rb:77:in `report'
     # ./lib/rspec/core/runner.rb:113:in `run_specs'
     # ./lib/rspec/core/runner.rb:89:in `run'
     # ./lib/rspec/core/runner.rb:73:in `run'
     # ./lib/rspec/core/runner.rb:41:in `invoke'
     # ./exe/rspec:4:in `<top (required)>'
     # bin/rspec:12:in `load'
     # bin/rspec:12:in `<main>'

  2) command line --order rand:SEED runs the examples and groups in the same order each time
     Failure/Error: write_file 'spec/simple_spec.rb', "
     Errno::ENOENT:
       No such file or directory @ dir_chdir - /Users/myron/code/rspec-dev/repos/rspec-core/tmp/aruba
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/core.rb:143:in `expand_path'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/filesystem.rb:123:in `write_file'
     # ./spec/integration/order_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./lib/rspec/core/hooks.rb:357:in `instance_exec'
     # ./lib/rspec/core/hooks.rb:357:in `run'
     # ./lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:520:in `each'
     # ./lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:473:in `run'
     # ./lib/rspec/core/example_group.rb:472:in `block in run_before_context_hooks'
     # ./lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
     # ./lib/rspec/core/example_group.rb:471:in `run_before_context_hooks'
     # ./lib/rspec/core/example_group.rb:520:in `run'
     # ./lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./lib/rspec/core/runner.rb:115:in `map'
     # ./lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./lib/rspec/core/configuration.rb:1632:in `with_suite_hooks'
     # ./lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./lib/rspec/core/reporter.rb:77:in `report'
     # ./lib/rspec/core/runner.rb:113:in `run_specs'
     # ./lib/rspec/core/runner.rb:89:in `run'
     # ./lib/rspec/core/runner.rb:73:in `run'
     # ./lib/rspec/core/runner.rb:41:in `invoke'
     # ./exe/rspec:4:in `<top (required)>'
     # bin/rspec:12:in `load'
     # bin/rspec:12:in `<main>'

  3) command line --seed SEED forces '--order rand' and runs the examples and groups in the same order each time
     Failure/Error: write_file 'spec/simple_spec.rb', "
     Errno::ENOENT:
       No such file or directory @ dir_chdir - /Users/myron/code/rspec-dev/repos/rspec-core/tmp/aruba
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/core.rb:143:in `expand_path'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/filesystem.rb:123:in `write_file'
     # ./spec/integration/order_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./lib/rspec/core/hooks.rb:357:in `instance_exec'
     # ./lib/rspec/core/hooks.rb:357:in `run'
     # ./lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:520:in `each'
     # ./lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:473:in `run'
     # ./lib/rspec/core/example_group.rb:472:in `block in run_before_context_hooks'
     # ./lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
     # ./lib/rspec/core/example_group.rb:471:in `run_before_context_hooks'
     # ./lib/rspec/core/example_group.rb:520:in `run'
     # ./lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./lib/rspec/core/runner.rb:115:in `map'
     # ./lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./lib/rspec/core/configuration.rb:1632:in `with_suite_hooks'
     # ./lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./lib/rspec/core/reporter.rb:77:in `report'
     # ./lib/rspec/core/runner.rb:113:in `run_specs'
     # ./lib/rspec/core/runner.rb:89:in `run'
     # ./lib/rspec/core/runner.rb:73:in `run'
     # ./lib/rspec/core/runner.rb:41:in `invoke'
     # ./exe/rspec:4:in `<top (required)>'
     # bin/rspec:12:in `load'
     # bin/rspec:12:in `<main>'

  4) command line --seed SEED runs examples in the same order, regardless of the order in which files are given
     Failure/Error: write_file 'spec/simple_spec.rb', "
     Errno::ENOENT:
       No such file or directory @ dir_chdir - /Users/myron/code/rspec-dev/repos/rspec-core/tmp/aruba
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/core.rb:143:in `expand_path'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/filesystem.rb:123:in `write_file'
     # ./spec/integration/order_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./lib/rspec/core/hooks.rb:357:in `instance_exec'
     # ./lib/rspec/core/hooks.rb:357:in `run'
     # ./lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:520:in `each'
     # ./lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:473:in `run'
     # ./lib/rspec/core/example_group.rb:472:in `block in run_before_context_hooks'
     # ./lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
     # ./lib/rspec/core/example_group.rb:471:in `run_before_context_hooks'
     # ./lib/rspec/core/example_group.rb:520:in `run'
     # ./lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./lib/rspec/core/runner.rb:115:in `map'
     # ./lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./lib/rspec/core/configuration.rb:1632:in `with_suite_hooks'
     # ./lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./lib/rspec/core/reporter.rb:77:in `report'
     # ./lib/rspec/core/runner.rb:113:in `run_specs'
     # ./lib/rspec/core/runner.rb:89:in `run'
     # ./lib/rspec/core/runner.rb:73:in `run'
     # ./lib/rspec/core/runner.rb:41:in `invoke'
     # ./exe/rspec:4:in `<top (required)>'
     # bin/rspec:12:in `load'
     # bin/rspec:12:in `<main>'

  5) command line --order defined on CLI with --order rand in .rspec overrides --order rand with --order defined
     Failure/Error: write_file 'spec/simple_spec.rb', "
     Errno::ENOENT:
       No such file or directory @ dir_chdir - /Users/myron/code/rspec-dev/repos/rspec-core/tmp/aruba
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/core.rb:143:in `expand_path'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/filesystem.rb:123:in `write_file'
     # ./spec/integration/order_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./lib/rspec/core/hooks.rb:357:in `instance_exec'
     # ./lib/rspec/core/hooks.rb:357:in `run'
     # ./lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:520:in `each'
     # ./lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:473:in `run'
     # ./lib/rspec/core/example_group.rb:472:in `block in run_before_context_hooks'
     # ./lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
     # ./lib/rspec/core/example_group.rb:471:in `run_before_context_hooks'
     # ./lib/rspec/core/example_group.rb:520:in `run'
     # ./lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./lib/rspec/core/runner.rb:115:in `map'
     # ./lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./lib/rspec/core/configuration.rb:1632:in `with_suite_hooks'
     # ./lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./lib/rspec/core/reporter.rb:77:in `report'
     # ./lib/rspec/core/runner.rb:113:in `run_specs'
     # ./lib/rspec/core/runner.rb:89:in `run'
     # ./lib/rspec/core/runner.rb:73:in `run'
     # ./lib/rspec/core/runner.rb:41:in `invoke'
     # ./exe/rspec:4:in `<top (required)>'
     # bin/rspec:12:in `load'
     # bin/rspec:12:in `<main>'

  6) command line when a custom order is configured orders the groups and examples by the provided strategy
     Failure/Error: write_file 'spec/simple_spec.rb', "
     Errno::ENOENT:
       No such file or directory @ dir_chdir - /Users/myron/code/rspec-dev/repos/rspec-core/tmp/aruba
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/platform.rb:75:in `chdir'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/core.rb:143:in `expand_path'
     # ./bundle/ruby/2.1.0/gems/aruba-0.8.0/lib/aruba/api/filesystem.rb:123:in `write_file'
     # ./spec/integration/order_spec.rb:7:in `block (2 levels) in <top (required)>'
     # ./lib/rspec/core/hooks.rb:357:in `instance_exec'
     # ./lib/rspec/core/hooks.rb:357:in `run'
     # ./lib/rspec/core/hooks.rb:521:in `block in run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:520:in `each'
     # ./lib/rspec/core/hooks.rb:520:in `run_owned_hooks_for'
     # ./lib/rspec/core/hooks.rb:473:in `run'
     # ./lib/rspec/core/example_group.rb:472:in `block in run_before_context_hooks'
     # ./lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
     # ./lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
     # ./lib/rspec/core/example_group.rb:471:in `run_before_context_hooks'
     # ./lib/rspec/core/example_group.rb:520:in `run'
     # ./lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs'
     # ./lib/rspec/core/runner.rb:115:in `map'
     # ./lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs'
     # ./lib/rspec/core/configuration.rb:1632:in `with_suite_hooks'
     # ./lib/rspec/core/runner.rb:114:in `block in run_specs'
     # ./lib/rspec/core/reporter.rb:77:in `report'
     # ./lib/rspec/core/runner.rb:113:in `run_specs'
     # ./lib/rspec/core/runner.rb:89:in `run'
     # ./lib/rspec/core/runner.rb:73:in `run'
     # ./lib/rspec/core/runner.rb:41:in `invoke'
     # ./exe/rspec:4:in `<top (required)>'
     # bin/rspec:12:in `load'
     # bin/rspec:12:in `<main>'

Finished in 0.00252 seconds (files took 0.18487 seconds to load)
6 examples, 6 failures

Failed examples:

rspec ./spec/integration/order_spec.rb:83 # command line --order rand runs the examples and groups in a different order each time
rspec ./spec/integration/order_spec.rb:100 # command line --order rand:SEED runs the examples and groups in the same order each time
rspec ./spec/integration/order_spec.rb:113 # command line --seed SEED forces '--order rand' and runs the examples and groups in the same order each time
rspec ./spec/integration/order_spec.rb:124 # command line --seed SEED runs examples in the same order, regardless of the order in which files are given
rspec ./spec/integration/order_spec.rb:136 # command line --order defined on CLI with --order rand in .rspec overrides --order rand with --order defined
rspec ./spec/integration/order_spec.rb:173 # command line when a custom order is configured orders the groups and examples by the provided strategy

Randomized with seed 21512
```

**Comment by maxmeyer** [comment]
Found some minutes. When is `before(:each) { }` run? And when `before(:all) {}`. As a workaround you could either add `  before(:all) { setup_aruba } ` before `run_command` in `aruba_support`.

**Comment by myronmarston** [comment]
> Found some minutes time. When is before(:each) { } run? And when before(:all) {}

The hook docs show when they run:

https://relishapp.com/rspec/rspec-core/v/3-3/docs/hooks/before-and-after-hooks

> As a workaround you could either add before(:all) { setup_aruba } before run_command in aruba_support.

Honestly, I don't have much time to mess around with work arounds. Aruba 0.6.2 works great for us so we don't have any reason to upgrade other than to "stay current".  I'd prefer to wait and upgrade to 0.8.1 (or whatever) once you've fixed the bug.

**Comment by dg-ratiodata** [comment]
Ok. Fixed. Please give it another try. I also sent you a PR with some suggestions on how to improve your aruba integration. 

BTW: I use a different algorithm to expand_paths now. There are also some feature tests added to prevent it to happen again.
