### ISSUE TITLE
Setting RUBYLIB works but not $LOAD_PATH

### ISSUE THREAD

**Issue by mbigras** [cucumber/aruba#556]
## Summary

Setting the `$LOAD_PATH` global doesn't work as expected.

## Expected Behavior

Given the following directory structure [mbigras/hello_aruba](https://github.com/mbigras/hello_aruba) rev `d5de011`

```
tree
.
├── Gemfile
├── Gemfile.lock
├── exe
│   └── hello_aruba
├── features
│   ├── cli.feature
│   ├── ruby.feature
│   └── support
│       └── env.rb
├── lib
│   ├── hello_aruba
│   │   └── version.rb
│   └── hello_aruba.rb
└── tmp
    └── aruba

7 directories, 8 files
```

And the contents of `env.rb`

```
grep -v '^#' features/support/env.rb
LIB_DIR = File.expand_path("../../../lib", __FILE__)
$LOAD_PATH.unshift(LIB_DIR)

require 'aruba/cucumber'
```

Cucumber should be able to find my `lib/hello_aruba.rb` file when it's required in `exe/hello_aruba`

```
cat exe/hello_aruba
#!/usr/bin/env ruby
require 'hello_aruba'

if ARGV.include?("--version")
  puts HelloAruba::VERSION
else
  puts "hello world!"
end
```

## Current Behavior

```
cucumber features/cli.feature:4
Feature: Run a basic CLI

<<-STDERR
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- hello_aruba (LoadError)
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /app/exe/hello_aruba:2:in `<main>'

STDERR

  # @announce
  @announce-stderr
  Scenario: Running the cli   # features/cli.feature:4
    When I run `hello_aruba`  # aruba-0.14.5/lib/aruba/cucumber/command.rb:13
<<-STDERR
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- hello_aruba (LoadError)
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /app/exe/hello_aruba:2:in `<main>'

STDERR

    Then it should pass with: # aruba-0.14.5/lib/aruba/cucumber/command.rb:299
      """
      hello world!
      """
      expected "hello_aruba" to be successfully executed (RSpec::Expectations::ExpectationNotMetError)
      features/cli.feature:6:in `Then it should pass with:'

Failing Scenarios:
cucumber features/cli.feature:4 # Scenario: Running the cli

1 scenario (1 failed)
2 steps (1 failed, 1 passed)
0m0.156s
```

## Possible Solution

I can get around this by setting the RUBYLIB environment variable:

```
cat features/support/env.rb
LIB_DIR = File.expand_path("../../../lib", __FILE__)
# $LOAD_PATH.unshift(LIB_DIR)

require 'aruba/cucumber'

Before do
  @original_rubylib = ENV['RUBYLIB']
  ENV['RUBYLIB'] = LIB_DIR + File::PATH_SEPARATOR + ENV['RUBYLIB'].to_s
end

After do
  ENV['RUBYLIB'] = @original_rubylib
end
```
```
cucumber features/cli.feature:4
Feature: Run a basic CLI

<<-STDERR

STDERR

  # @announce
  @announce-stderr
  Scenario: Running the cli   # features/cli.feature:4
    When I run `hello_aruba`  # aruba-0.14.5/lib/aruba/cucumber/command.rb:13
<<-STDERR

STDERR

<<-STDERR

STDERR

    Then it should pass with: # aruba-0.14.5/lib/aruba/cucumber/command.rb:299
      """
      hello world!
      """

1 scenario (1 passed)
2 steps (2 passed)
0m0.224s
```

My understanding is RUBYLIB and $LOAD_PATH represent the same thing: the lookup path for Ruby library files. Shouldn't both these approaches work?

## Steps to Reproduce (for bugs)

```
git clone https://github.com/mbigras/hello_aruba
cd hello_aruba
git checkout d5de011
docker build --tag hello_aruba .
bin/cucumber
```

## Context & Motivation

I want to be confident in the tool I'm using to be confident in the tools I'm building :)

## Your Environment

```
cat /etc/*elease
3.7.0
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

**Comment by mbigras** [comment]
This issues comes from not understanding how Ruby's `$LOAD_PATH` works.

Aruba's `$LOAD_PATH` inside `env.rb` is different from `hello_aruba`'s `$LOAD_PATH`.

The reason using `ENV['RUBYLIB']` works is because setting that exports it as an environment variable which reaches both Aruba and `hello_aruba`.
