### ISSUE TITLE
wrong number of arguments (given 0, expected 1) (ArgumentError) from lambda in ParameterTypeRegistry

### ISSUE THREAD

**Issue by davetron5000** [cucumber/aruba#558]
## Summary

Upgrading an app from older versions of Cucumber and Aruba, and the step "When I successfully run `foobar`" is failing from inside Cucumber's cucumber-expression gem and I have no idea how to proceed with debugging.

## Expected Behavior

I would expect the step to either clearly succeed or fail and not generate an exception from Cucumber's internals.

## Current Behavior

```ruby
# foo.feature
Scenario: A thing
  When I do a thing
  Then I expect a thing

# step_definitions/foo.rb
When("I do a thing") do
  step "I successfully `ls`"
end

Then("I expect a thing") do
end
```

This results in the  stack trace below.

Partial:

```
wrong number of arguments (given 0, expected 1) (ArgumentError)
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type_registry.rb:17:in `block in initialize'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type.rb:38:in `instance_exec'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type.rb:38:in `transform'
«tons elided; full trace below»
```

When I traced this into `parameter_type_registry.rb`, it's from this code:

```ruby
def initialize
  @parameter_type_by_name = {}
  @parameter_types_by_regexp = Hash.new {|hash, regexp| hash[regexp] = []}

  define_parameter_type(ParameterType.new('int', INTEGER_REGEXPS, Integer, lambda {|s| s.to_i}, true, true))
  define_parameter_type(ParameterType.new('float', FLOAT_REGEXP, Float, lambda {|s| s.to_f}, true, false))
  define_parameter_type(ParameterType.new('word', WORD_REGEXP, String, lambda {|s| s}, false, false))
  define_parameter_type(ParameterType.new('string', STRING_REGEXP, String, lambda {|s| s.gsub(/\\"/, '"').gsub(/\\'/, "'")}, true, false))
end
```

The exception is coming from Ruby's attempt to invoke the lambda passed to the first `define_parameter_type`.  If I replace that lambda with one that accepts any arguments, it gets farther, and I get:

```
expected "ls" to have finished in time (RSpec::Expectations::ExpectationNotMetError)
```

So, something is wrong inside Aruba's "When I successfully run".

## Environment

```
> uname -a
Darwin Davids-MBP-3.fios-router.home 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
> ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
> grep cucumber Gemfile.lock 
      cucumber (>= 1.3.19)
    cucumber (3.1.0)
      cucumber-core (~> 3.1.0)
      cucumber-expressions (~> 5.0.4)
      cucumber-wire (~> 0.0.1)
    cucumber-core (3.1.0)
      cucumber-tag_expressions (~> 1.1.0)
    cucumber-expressions (5.0.17)
    cucumber-tag_expressions (1.1.1)
    cucumber-wire (0.0.1)
  cucumber
> grep aruba Gemfile.lock 
    aruba (0.14.5)
  aruba
```

## Full stack trace

```
wrong number of arguments (given 0, expected 1) (ArgumentError)
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type_registry.rb:17:in `block in initialize'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type.rb:38:in `instance_exec'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/parameter_type.rb:38:in `transform'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-expressions-5.0.17/lib/cucumber/cucumber_expressions/argument.rb:33:in `value'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:18:in `block in args'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:17:in `map'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:17:in `args'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:97:in `deep_clone_args'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:29:in `invoke'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/step_match.rb:24:in `block in activate'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/action.rb:24:in `execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/step.rb:32:in `execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:104:in `execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:51:in `execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:27:in `test_step'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/step.rb:17:in `describe_to'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:28:in `block (3 levels) in describe_to'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:27:in `each'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:27:in `block (2 levels) in describe_to'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/filters/prepare_world.rb:23:in `block in test_case'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/around_hook.rb:17:in `execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:104:in `execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:51:in `execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:34:in `around_hook'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:120:in `block (2 levels) in compose_around_hooks'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:121:in `compose_around_hooks'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:26:in `block in describe_to'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:19:in `test_case'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/filters/prepare_world.rb:12:in `test_case'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:57:in `test_case'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/filters/retry.rb:18:in `test_case'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/filters/quit.rb:12:in `test_case'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `block in done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:19:in `map'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:19:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/locations_filter.rb:20:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/compiler.rb:24:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:32:in `parse'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:21:in `compile'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/runtime.rb:74:in `run!'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:33:in `execute!'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/cli/main.rb:12:in `execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/rake/task.rb:48:in `run'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/cucumber-3.1.0/lib/cucumber/rake/task.rb:148:in `block in define_task'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
      /Users/davec/.asdf/installs/ruby/2.5.1/bin/rake:23:in `load'
      /Users/davec/.asdf/installs/ruby/2.5.1/bin/rake:23:in `<top (required)>'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
      /Users/davec/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
      /Users/davec/.asdf/installs/ruby/2.5.1/bin/bundle:23:in `load'
      /Users/davec/.asdf/installs/ruby/2.5.1/bin/bundle:23:in `<main>'
      features/bootstrap.feature:12:in `When I successfully run `methadone tmp/newgem`'
```

**Comment by xtrasimplicity** [comment]
> it gets farther, and I get:

``expected "ls" to have finished in time (RSpec::Expectations::ExpectationNotMetError)``
> So, something is wrong inside Aruba's "When I successfully run".

What happens if you change `when I successfully run` to `when I run`?

**Comment by davetron5000** [comment]
It works fine and there is no error (with or without my changes to
Cucumber's internals)

Dave

**Comment by davetron5000** [comment]
Confirmed that downgrading to 2.x does not have this problem. It looks like while the latest release of aruba has an open-ended dep, master has it constrained, so sounds like the next release will prevent this error from showing up until Cuke 3 is supported.

Thanks all!
