### ISSUE TITLE
Test errors on guix

### ISSUE THREAD

**Issue by swedebugia** [cucumber/aruba#589]
Im guix we run the tests in an isolated environment with ruby version ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux].

We currently get these errors:

```
Randomized with seed 46150
............................../tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
/tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
./tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
/tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
./tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
./tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
......................................................................................................................................F.....F.F......................................../tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
/tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
./tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
/tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
................................../tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
./tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/processes/basic_process.rb:100: warning: instance variable @timed_out not initialized
................../tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/runtime.rb:84: warning: instance variable @fixtures_directory not initialized
......../tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/lib/aruba/runtime.rb:84: warning: instance variable @fixtures_directory not initialized
.......FF.....FF...............................................................

Failures:

  1) Command Matchers #to_have_output_on_stdout when have output hello world on stderr
     Failure/Error: raise LaunchError, "It tried to start #{cmd}. " + e.message

     NameError:
       undefined local variable or method `cmd' for #<Aruba::Processes::SpawnProcess:0x0000555556f0bc10>
       Did you mean?  @cmd
     # ./lib/aruba/processes/spawn_process.rb:89:in `rescue in start'
     # ./lib/aruba/processes/spawn_process.rb:83:in `start'
     # ./lib/aruba/command.rb:69:in `start'
     # ./lib/aruba/api/command.rb:213:in `run'
     # ./spec/aruba/matchers/command_spec.rb:126:in `block (4 levels) in <top (required)>'
     # ./lib/aruba/rspec.rb:22:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ChildProcess::LaunchError:
     #   No such file or directory - /tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/tmp/aruba/cmd.sh
     #   ./lib/aruba/processes/spawn_process.rb:85:in `block in start'

  2) Command Matchers #to_have_output when have output hello world on stderr
     Failure/Error: raise LaunchError, "It tried to start #{cmd}. " + e.message

     NameError:
       undefined local variable or method `cmd' for #<Aruba::Processes::SpawnProcess:0x00005555571159e8>
       Did you mean?  @cmd
     # ./lib/aruba/processes/spawn_process.rb:89:in `rescue in start'
     # ./lib/aruba/processes/spawn_process.rb:83:in `start'
     # ./lib/aruba/command.rb:69:in `start'
     # ./lib/aruba/api/command.rb:213:in `run'
     # ./spec/aruba/matchers/command_spec.rb:89:in `block (4 levels) in <top (required)>'
     # ./lib/aruba/rspec.rb:22:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ChildProcess::LaunchError:
     #   No such file or directory - /tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/tmp/aruba/cmd.sh
     #   ./lib/aruba/processes/spawn_process.rb:85:in `block in start'

  3) Command Matchers #to_have_output_on_stderr when have output hello world on stderr
     Failure/Error: raise LaunchError, "It tried to start #{cmd}. " + e.message

     NameError:
       undefined local variable or method `cmd' for #<Aruba::Processes::SpawnProcess:0x0000555556efd4a8>
       Did you mean?  @cmd
     # ./lib/aruba/processes/spawn_process.rb:89:in `rescue in start'
     # ./lib/aruba/processes/spawn_process.rb:83:in `start'
     # ./lib/aruba/command.rb:69:in `start'
     # ./lib/aruba/api/command.rb:213:in `run'
     # ./spec/aruba/matchers/command_spec.rb:163:in `block (4 levels) in <top (required)>'
     # ./lib/aruba/rspec.rb:22:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ChildProcess::LaunchError:
     #   No such file or directory - /tmp/guix-build-ruby-aruba-0.14.7.drv-0/gem/tmp/aruba/cmd.sh
     #   ./lib/aruba/processes/spawn_process.rb:85:in `block in start'

  4) Aruba::Api files #touch when directory when exist and the mtime should be set statically
     Failure/Error: let(:options) { { :mtime => Time.parse('2014-01-01 10:00:00') } }

     NoMethodError:
       undefined method `parse' for Time:Class
     # ./spec/aruba/api_spec.rb:386:in `block (7 levels) in <top (required)>'
     # ./spec/aruba/api_spec.rb:381:in `block (6 levels) in <top (required)>'
     # ./lib/aruba/rspec.rb:22:in `block (2 levels) in <top (required)>'

  5) Aruba::Api files #touch when directory when exist and the mtime should be set statically behaves like an existing directory
     Failure/Error: let(:options) { { :mtime => Time.parse('2014-01-01 10:00:00') } }

     NoMethodError:
       undefined method `parse' for Time:Class
     Shared Example Group: "an existing directory" called from ./spec/aruba/api_spec.rb:388
     # ./spec/aruba/api_spec.rb:386:in `block (7 levels) in <top (required)>'
     # ./spec/aruba/api_spec.rb:381:in `block (6 levels) in <top (required)>'
     # ./lib/aruba/rspec.rb:22:in `block (2 levels) in <top (required)>'

  6) Aruba::Api files #touch when file when does not exist and the mtime should be set statically
     Failure/Error: let(:options) { { :mtime => Time.parse('2014-01-01 10:00:00') } }

     NoMethodError:
       undefined method `parse' for Time:Class
     # ./spec/aruba/api_spec.rb:359:in `block (7 levels) in <top (required)>'
     # ./spec/aruba/api_spec.rb:333:in `block (5 levels) in <top (required)>'
     # ./lib/aruba/rspec.rb:22:in `block (2 levels) in <top (required)>'

  7) Aruba::Api files #touch when file when does not exist and the mtime should be set statically behaves like an existing file
     Failure/Error: let(:options) { { :mtime => Time.parse('2014-01-01 10:00:00') } }

     NoMethodError:
       undefined method `parse' for Time:Class
     Shared Example Group: "an existing file" called from ./spec/aruba/api_spec.rb:361
     # ./spec/aruba/api_spec.rb:359:in `block (7 levels) in <top (required)>'
     # ./spec/aruba/api_spec.rb:333:in `block (5 levels) in <top (required)>'
     # ./lib/aruba/rspec.rb:22:in `block (2 levels) in <top (required)>' 
```

any ideas?

**Comment by olleolleolle** [comment]
@swedebugia Just for completeness, can you add which Git commit you used?

**Comment by olleolleolle** [comment]
The `cmd` seems to be there, still! You have probably _found a defect_!

What happens if you name it `@cmd` instead, on the line which fails?

**Comment by rekado** [comment]
> @swedebugia Just for completeness, can you add which Git commit you used?
> 
> Would it match this (Git tag `0.14.7`)?
> 
> https://github.com/cucumber/aruba/blob/v0.14.7/lib/aruba/processes/spawn_process.rb#L89

We used the gem for version 0.14.7, downloaded from https://rubygems.org/downloads/aruba-0.14.7.gem.

**Comment by swedebugia** [comment]
Works with latest master. Closing.
