### ISSUE TITLE
cucumber test fails with Minitest 5.22.2

### ISSUE THREAD

**Issue by mtasaka** [cucumber/aruba#920]
With Minitest 5.22.2, perhaps due to https://github.com/minitest/minitest/commit/ef839657fe46ecda4f46a6c0fdc670a361374080 , some behavior changed. 

Perviously, if there was no tests actually, Minitest showed the message like:
```
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```
With Minitest 5.22.2, the above message won't be shown.
(Messages like "Run options: --seed 28982" are shown, but the above "0 errors" messages
 won't appear)

Now with Minitest 5.22.2 , aruba git head (I tried b9d0f15d1292697b051f94984925b4f63c4efac4 ) cucumber test fails like:
```
+ env RUBYOPT=-I/builddir/build/GIT/aruba/lib cucumber -f progress

(::) failed steps (::)

expected "Run options: --seed 23579\n\n# Running:\n" to string includes: "0 errors"
Diff:
@@ -1,3 +1,5 @@
-0 errors
+Run options: --seed 23579
+
+# Running:
 (RSpec::Expectations::ExpectationNotMetError)
./lib/aruba/cucumber/command.rb:126:in `nil'
./lib/aruba/cucumber/testing_frameworks.rb:95:in `/^the tests(?:s)? should all pass$/'
./features/support/timing.rb:9:in `block in <top (required)>'
./lib/aruba/platforms/local_environment.rb:22:in `call'
./lib/aruba/platforms/unix_platform.rb:79:in `with_environment'
./lib/aruba/api/core.rb:222:in `block in with_environment'
./lib/aruba/platforms/unix_environment_variables.rb:189:in `nest'
./lib/aruba/api/core.rb:220:in `with_environment'
./lib/aruba/cucumber/hooks.rb:7:in `block in <top (required)>'
features/01_getting_started_with_aruba/supported_testing_frameworks.feature:88:in `the tests should all pass'

expected "      create  test/test_helper.rb\n      create  test/use_aruba_with_minitest.rb\n      create  Gemfile\nRun options: --seed 26522\n\n# Running:\n" to string includes: "0 runs, 0 assertions, 0 failures, 0 errors, 0 skips"
Diff:
@@ -1,6 +1,11 @@
-0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
+      create  test/test_helper.rb
+      create  test/use_aruba_with_minitest.rb
+      create  Gemfile
+Run options: --seed 26522
+
+# Running:
 (RSpec::Expectations::ExpectationNotMetError)
./lib/aruba/cucumber/command.rb:216:in `nil'
./features/support/timing.rb:9:in `block in <top (required)>'
./lib/aruba/platforms/local_environment.rb:22:in `call'
./lib/aruba/platforms/unix_platform.rb:79:in `with_environment'
./lib/aruba/api/core.rb:222:in `block in with_environment'
./lib/aruba/platforms/unix_environment_variables.rb:189:in `nest'
./lib/aruba/api/core.rb:220:in `with_environment'
./lib/aruba/cucumber/hooks.rb:7:in `block in <top (required)>'
features/06_use_aruba_cli/initialize_project_with_aruba.feature:69:in `the output should contain:'

Failing Scenarios:
cucumber features/01_getting_started_with_aruba/supported_testing_frameworks.feature:57 # Scenario: Use "aruba" with "Minitest"
cucumber features/06_use_aruba_cli/initialize_project_with_aruba.feature:60 # Scenario: Create files for Minitest
```

**Comment by mvz** [comment]
This will be fixed in #921.
